name: build-mod
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # 直接下載 Gradle 8.8（不靠 apt），生成正牌 wrapper 並賦予執行權限
      - name: Generate Gradle wrapper (8.8)
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.8-bin.zip -o gradle-8.8-bin.zip
          unzip -q gradle-8.8-bin.zip
          ./gradle-8.8/bin/gradle --version
          ./gradle-8.8/bin/gradle wrapper --gradle-version 8.8
          chmod +x gradlew

      - name: Build with wrapper
        run: ./gradlew --no-daemon --stacktrace --info build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-enchant-mod
          path: build/libs/*.jar
